/**
 * Premium PDF generator built on jsPDF (text-based, searchable, lightweight).
 *
 * Features:
 *   - Branded cover page with gradient block, document title, generated date
 *   - Diagonal "MeraBakil — Draft" watermark on every body page
 *   - Header (template name) and footer (page number + disclaimer) on every page
 *   - Justified paragraphs with automatic page breaks
 *   - Heading styling for `## SECTION` lines
 *   - Signature blocks at the end with name/date underlines
 *
 * jsPDF is lazy-loaded so it never lands in the initial chunk.
 */

import { renderTemplate } from './renderTemplate';

const A4_W = 210;
const A4_H = 297;
const MARGIN_X = 18;
const MARGIN_TOP = 22;
const MARGIN_BOTTOM = 22;
const LINE_HEIGHT = 5.6;
const HEADING_GAP_BEFORE = 4;
const HEADING_GAP_AFTER = 2.5;
const PARA_GAP = 3;

const drawWatermark = (doc) => {
  doc.saveGraphicsState();
  doc.setTextColor(180, 180, 180);
  doc.setFontSize(56);
  doc.setFont('times', 'bold');
  // jsPDF has setGState but availability varies; fall back gracefully.
  try {
    const gState = new doc.GState({ opacity: 0.08 });
    doc.setGState(gState);
  } catch (e) {
    // ignore — older versions of jsPDF
  }
  doc.text('MERABAKIL', A4_W / 2, A4_H / 2, {
    align: 'center',
    angle: 30,
  });
  doc.restoreGraphicsState();
  doc.setTextColor(0, 0, 0);
};

const drawHeader = (doc, title) => {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(title, MARGIN_X, 12);
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.2);
  doc.line(MARGIN_X, 14, A4_W - MARGIN_X, 14);
  doc.setTextColor(0, 0, 0);
};

const drawFooter = (doc, pageNumber, totalPages) => {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(140, 140, 140);
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN_X, A4_H - 16, A4_W - MARGIN_X, A4_H - 16);
  const disclaimer =
    'This is a draft generated by MeraBakil. Please consult a qualified legal professional before signing.';
  doc.text(disclaimer, MARGIN_X, A4_H - 11);
  doc.text(`Page ${pageNumber} of ${totalPages}`, A4_W - MARGIN_X, A4_H - 11, { align: 'right' });
  doc.setTextColor(0, 0, 0);
};

const drawCoverPage = (doc, template, generatedOn) => {
  // Gradient-ish coloured band at the top using two stacked rectangles.
  doc.setFillColor(37, 99, 235); // blue-600
  doc.rect(0, 0, A4_W, 70, 'F');
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 60, A4_W, 12, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text('MERA BAKIL  |  LEGAL DOCUMENTS', MARGIN_X, 22);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Premium Document Generation', MARGIN_X, 28);

  // Title block
  doc.setTextColor(15, 23, 42);
  doc.setFont('times', 'bold');
  doc.setFontSize(26);
  const titleLines = doc.splitTextToSize(template.name, A4_W - MARGIN_X * 2);
  doc.text(titleLines, MARGIN_X, 110);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const descLines = doc.splitTextToSize(template.description || '', A4_W - MARGIN_X * 2);
  doc.text(descLines, MARGIN_X, 130);

  // Meta block
  const metaY = 180;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_X, metaY, A4_W - MARGIN_X, metaY);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('GENERATED ON', MARGIN_X, metaY + 8);
  doc.text('JURISDICTION', MARGIN_X + 70, metaY + 8);
  doc.text('TEMPLATE ID', MARGIN_X + 130, metaY + 8);

  doc.setFont('times', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(generatedOn, MARGIN_X, metaY + 15);
  doc.text(template.jurisdiction || 'India', MARGIN_X + 70, metaY + 15);
  doc.text(template.id, MARGIN_X + 130, metaY + 15);

  doc.line(MARGIN_X, metaY + 22, A4_W - MARGIN_X, metaY + 22);

  // Footer band
  doc.setFillColor(15, 23, 42);
  doc.rect(0, A4_H - 28, A4_W, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Smart. Beautiful. Legal.', MARGIN_X, A4_H - 17);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(203, 213, 225);
  doc.text(
    'This document is a customisable draft. Always have it reviewed by a qualified advocate before execution.',
    MARGIN_X,
    A4_H - 10
  );

  doc.setTextColor(0, 0, 0);
};

const renderBlocks = (doc, blocks, title) => {
  let y = MARGIN_TOP;
  let pageNumber = 2; // we already drew the cover page

  const newPage = () => {
    doc.addPage();
    pageNumber += 1;
    drawWatermark(doc);
    drawHeader(doc, title);
    y = MARGIN_TOP;
  };

  const ensureSpace = (needed) => {
    if (y + needed > A4_H - MARGIN_BOTTOM) {
      newPage();
    }
  };

  drawWatermark(doc);
  drawHeader(doc, title);

  blocks.forEach((block) => {
    if (block.type === 'heading') {
      ensureSpace(HEADING_GAP_BEFORE + LINE_HEIGHT + HEADING_GAP_AFTER);
      y += HEADING_GAP_BEFORE;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11.5);
      doc.setTextColor(15, 23, 42);
      const headingLines = doc.splitTextToSize(block.text, A4_W - MARGIN_X * 2);
      headingLines.forEach((line) => {
        ensureSpace(LINE_HEIGHT);
        doc.text(line, MARGIN_X, y);
        y += LINE_HEIGHT;
      });
      // Underline accent
      doc.setDrawColor(37, 99, 235);
      doc.setLineWidth(0.6);
      doc.line(MARGIN_X, y - 1, MARGIN_X + 10, y - 1);
      y += HEADING_GAP_AFTER;
      return;
    }
    // paragraph
    doc.setFont('times', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    const lines = doc.splitTextToSize(block.text, A4_W - MARGIN_X * 2);
    lines.forEach((line) => {
      ensureSpace(LINE_HEIGHT);
      doc.text(line, MARGIN_X, y, { align: 'justify', maxWidth: A4_W - MARGIN_X * 2 });
      y += LINE_HEIGHT;
    });
    y += PARA_GAP;
  });

  return pageNumber;
};

const renderSignatureBlocks = (doc, blocks, title) => {
  if (!blocks || !blocks.length) return doc.internal.getNumberOfPages();

  // Always start signatures on a fresh page so they don't crowd the body text.
  doc.addPage();
  drawWatermark(doc);
  drawHeader(doc, title);

  let y = MARGIN_TOP + 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(15, 23, 42);
  doc.text('SIGNATURES', MARGIN_X, y);
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.6);
  doc.line(MARGIN_X, y + 1, MARGIN_X + 18, y + 1);
  y += 14;

  doc.setFont('times', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(30, 41, 59);

  // Two-column layout
  const colWidth = (A4_W - MARGIN_X * 2 - 10) / 2;
  for (let i = 0; i < blocks.length; i += 1) {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = MARGIN_X + col * (colWidth + 10);
    const cy = y + row * 38;

    doc.setDrawColor(148, 163, 184);
    doc.setLineWidth(0.4);
    doc.line(x, cy + 10, x + colWidth - 6, cy + 10);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text((blocks[i] || '').toUpperCase(), x, cy + 16);

    doc.setFont('times', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text('Name: ____________________________', x, cy + 22);
    doc.text('Date:  ____________________________', x, cy + 28);
  }

  return doc.internal.getNumberOfPages();
};

const finaliseFooters = (doc, title) => {
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    if (i === 1) continue; // skip cover page footer
    drawFooter(doc, i, totalPages);
  }
};

/**
 * Build a Blob PDF for the given template + values. Lazy-loads jsPDF.
 *
 * @param {object} template
 * @param {object} values
 * @returns {Promise<{ blob: Blob, filename: string, dataUri: string }>}
 */
export const generatePdf = async (template, values) => {
  // Lazy-load jsPDF so it never lands in the initial bundle.
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true });
  const generatedOn = new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // Cover page
  drawCoverPage(doc, template, generatedOn);

  // Body pages
  const { blocks } = renderTemplate(template, values);
  renderBlocks(doc, blocks, template.name);

  // Signature page
  renderSignatureBlocks(doc, template.signatureBlocks || [], template.name);

  // Page numbers + disclaimer on every non-cover page
  finaliseFooters(doc, template.name);

  const blob = doc.output('blob');
  const dataUri = doc.output('datauristring');
  const safeName = (template.name || 'document').replace(/[^a-z0-9-_ ]/gi, '').replace(/\s+/g, '-');
  const filename = `MeraBakil-${safeName}-${Date.now()}.pdf`;
  return { blob, filename, dataUri };
};

/** Trigger a browser download for a generated PDF blob. */
export const downloadBlob = (blob, filename) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

export default generatePdf;
